### ISSUE TITLE
/usr/bin/ld: (...) relocation R_X86_64_PC32 against symbol `SuiteSparse_config' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by j-j-v** [siko1056/GNU-Octave-enable-64#14]
Hi, thanks for your great help last time.

I was able to get this to compile before, but when I try now I'm getting this error a ways into the make: 

/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libsuitesparseconfig.a(SuiteSparse_config.o): relocation R_X86_64_PC32 against symbol `SuiteSparse_config' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
make[5]: Leaving directory '/etc/skel/GNU-Octave-enable-64/build/suitesparse/Mongoose/build'
collect2: error: ld returned 1 exit status
make[5]: *** [CMakeFiles/mongoose_dylib.dir/build.make:505: lib/libmongoose.so.2.0.2] Error 1
make[5]: Leaving directory '/etc/skel/GNU-Octave-enable-64/build/suitesparse/Mongoose/build'
make[4]: *** [CMakeFiles/Makefile2:364: CMakeFiles/mongoose_dylib.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[ 65%] Built target mongoose_unit_test_edgesep
make[4]: Leaving directory '/etc/skel/GNU-Octave-enable-64/build/suitesparse/Mongoose/build'
make[3]: *** [Makefile:141: all] Error 2
make[3]: Leaving directory '/etc/skel/GNU-Octave-enable-64/build/suitesparse/Mongoose/build'
make[2]: *** [Makefile:28: install] Error 2
make[2]: Leaving directory '/etc/skel/GNU-Octave-enable-64/build/suitesparse/Mongoose'
make[1]: *** [Makefile:42: install] Error 2
make[1]: Leaving directory '/etc/skel/GNU-Octave-enable-64/build/suitesparse'
make: *** [Makefile:97: /etc/skel/GNU-Octave-enable-64/install/lib/libsuitesparseconfig_Octave64.so] Error 2

I am in a plain vanilla Kubuntu 18.10 & have as far as I know the Octave make dependencies fully satisfied. Thanks for any nudging on this. FWIW, the last time I wrote in (a little less than a year ago I think) the fix was to run make with -j2 rather than -j3 or s/t, & I will just say in advance that I have done that again here, but it hasn't worked this time. Thank you very much for this again. Great little weekend-project tool for me. 

Joe Valentyn

**Comment by siko1056** [comment]
Dear Joe,

Sorry for the late reply.  The line at the beginning of your error message
 
  /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/libsuitesparseconfig.a

looks like your build gets confused with installed system libraries.  I'll try myself if it still works for me.

Maybe you can try to rename that file temporary and see if it runs through?

Best,
Kai

**Comment by siko1056** [comment]
The issue cannot be reproduced by me. No response by @j-j-v . Closing report in hope the situation got fixed somehow.
