### ISSUE TITLE
wishlist: glpk

### ISSUE THREAD

**Issue by coalsont** [siko1056/GNU-Octave-enable-64#16]
System glpk depends on system suitesparse, and building with both -dev packages installed causes a segfault in "chol.cc-test", presumably from some conflict between system glpk pulling in system suitesparse, and the 64bit indexing suitesparse built by this makefile.

Is it possible to have it also build glpk against the custom suitesparse, just so that it can be available?  Personally, I don't think we use it, but it would be nice if it could be sorted out.

**Comment by siko1056** [comment]
Thank you for your interest.  Does it work, if you call

    make -j8 glpk

first and then

    make -j8

On my systems this caused the self-compiled glpk to be favored over the system glpk.

---

**Background information:**  I think you are using either Debian or Ubuntu.  Usually, glpk comes with a small subset of Suitesparse functions in it's source.  The Debian or Ubuntu packages of glpk removed that subset and force to link against the systems Suitesparse, which is often not necessary.

**Comment by coalsont** [comment]
Ah, I hadn't read closely enough.  Yes, I am using ubuntu, I will try that.

**Comment by coalsont** [comment]
Yes, that works, sorry for the noise.
